version: '1.0'
services:
  server_cont:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: python server.py
  client2:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: python client.py
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    entrypoint: python client.py
    port:
    - 2137:2137