version: '2.0'
services:
  server_cont:
    build:
      context: server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "2137"
    networks:
      static-network:
        ipv4_address: 172.20.0.254
    entrypoint: python server.py
  client1:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      static-network:
    entrypoint: python3 client.py -p 2137 -4 172.20.0.254
    depends_on: 
      - server_cont
    volumes:
      - ./logs/:/tictactoe/logs
  client2:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      static-network:
    entrypoint: python3 client.py -p 2137 -4 172.20.0.254
    depends_on: 
      - server_cont
    volumes:
      - ./logs/:/tictactoe/logs

networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

