version: '2.0'
services:
  server_cont:
    build:
      context: server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "2137"
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    entrypoint: python server.py
  client1:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      static-network:
    entrypoint: python client.py -p 2137 -4 172.20.128.2
  client2:
    build:
      context: client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    networks:
      static-network:
    entrypoint: python client.py -p 2137 -4 172.20.128.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24
